config/routes.rb
Rails.application.routes.draw do
  resources :artists
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :artist
  has_many :album_genres
  has_many :genres, through: :album_genres

  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
  validates :year, presence: true, length: { minimum: 4, maximum: 4 }
  validates :image_url, length: { maximum: 255 }
  validates :artist_id, presence: true
end

app/models/album_genre.rb
class AlbumGenre < ApplicationRecord
  belongs_to :album
  belongs_to :genre
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/artist.rb
class Artist < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maximum: 50 }
  validates :image_url, length: { maximum: 255 }
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :albums
  has_many :album_genres
  has_many :albums, through: :album_genres

  validates :title, presence: true, length: { minimum: 3, maximum: 50 }
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :album

  validates :name, presence: true, length: { minimum: 1, maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: %i[ show edit update destroy ]

  def index
    @artists = Artist.all
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)
      if @artist.save
        redirect_to artist_url(@artist), notice: "Artist was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
  end

  def update
    if @artist.update(artist_params)
      redirect_to artist_url(@artist), notice: "Artist was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @artist.destroy
    redirect_to artists_url, notice: "Artist was successfully destroyed."
  end

  private

  def set_artist
    @artist = Artist.find(params[:id])
  end

  def artist_params
    params.require(:artist).permit(:name, :bio, :image_url, :sites)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/artists/_artist.html.erb
<div id="<%= dom_id artist %>">
  <p>
    <strong>Name:</strong>
    <%= artist.name %>
  </p>

  <p>
    <strong>Bio:</strong>
    <%= artist.bio %>
  </p>

  <p>
    <strong>Image url:</strong>
    <%= artist.image_url %>
  </p>

  <p>
    <strong>Sites:</strong>
    <%= artist.sites %>
  </p>

</div>

app/views/artists/_form.html.erb
<%= form_with(model: artist) do |form| %>
  <% if artist.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
        <% artist.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :bio, style: "display: block" %>
    <%= form.text_area :bio %>
  </div>

  <div>
    <%= form.label :image_url, style: "display: block" %>
    <%= form.text_field :image_url %>
  </div>

  <div>
    <%= form.label :sites, style: "display: block" %>
    <%= form.text_area :sites %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<h1>Editing artist</h1>

<%= render "form", artist: @artist %>

<br>

<div>
  <%= link_to "Show this artist", @artist %> |
  <%= link_to "Back to artists", artists_path %>
</div>

app/views/artists/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Artists</h1>

<div id="artists">
  <% @artists.each do |artist| %>
    <%= render artist %>
    <p>
      <%= link_to "Show this artist", artist %>
    </p>
  <% end %>
</div>

<%= link_to "New artist", new_artist_path %>

app/views/artists/new.html.erb
<h1>New artist</h1>

<%= render "form", artist: @artist %>

<br>

<div>
  <%= link_to "Back to artists", artists_path %>
</div>

app/views/artists/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @artist %>

<div>
  <%= link_to "Edit this artist", edit_artist_path(@artist) %> |
  <%= link_to "Back to artists", artists_path %>

  <%= button_to "Destroy this artist", @artist, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Discogs</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>